export interface CountryFlagProps {
  country: string;
  size?: number;
  className?: string;
}

// Simple flat-color flags for the countries generated by createLeagueState.
// Falls back to a plain gray swatch for any country without a drawn flag.
export function CountryFlag({ country, size = 18, className }: CountryFlagProps) {
  const w = size;
  const h = Math.round((size * 2) / 3);
  const style = { width: w, height: h, display: "inline-block", verticalAlign: "middle" };
  const commonProps = {
    width: w,
    height: h,
    viewBox: "0 0 3 2",
    className: `country-flag${className ? ` ${className}` : ""}`,
    style,
    "aria-hidden": true,
  };

  switch (country) {
    case "England":
      return (
        <svg {...commonProps}>
          <rect width="3" height="2" fill="#ffffff" />
          <rect x="1.2" width="0.6" height="2" fill="#ce1124" />
          <rect y="0.7" width="3" height="0.6" fill="#ce1124" />
        </svg>
      );
    case "Spain":
      return (
        <svg {...commonProps}>
          <rect width="3" height="2" fill="#aa151b" />
          <rect y="0.5" width="3" height="1" fill="#f1bf00" />
        </svg>
      );
    case "Italy":
      return (
        <svg {...commonProps}>
          <rect width="1" height="2" fill="#009246" />
          <rect x="1" width="1" height="2" fill="#ffffff" />
          <rect x="2" width="1" height="2" fill="#ce2b37" />
        </svg>
      );
    case "Germany":
      return (
        <svg {...commonProps}>
          <rect width="3" height="2" fill="#000000" />
          <rect y="0.667" width="3" height="0.667" fill="#dd0000" />
          <rect y="1.333" width="3" height="0.667" fill="#ffce00" />
        </svg>
      );
    case "France":
      return (
        <svg {...commonProps}>
          <rect width="1" height="2" fill="#0055a4" />
          <rect x="1" width="1" height="2" fill="#ffffff" />
          <rect x="2" width="1" height="2" fill="#ef4135" />
        </svg>
      );
    case "Portugal":
      return (
        <svg {...commonProps}>
          <rect width="3" height="2" fill="#da291c" />
          <rect width="1.2" height="2" fill="#046a38" />
          <circle cx="1.2" cy="1" r="0.32" fill="#ffe600" />
        </svg>
      );
    default:
      return <span className="country-flag-fallback" style={style} />;
  }
}
