import { Link } from "react-router-dom";
import { useLeague } from "../context/LeagueContext.js";
import { HelpHint, PotHelp } from "../components/HelpHint.js";
import { canExtend, contractTerms } from "../../core/contracts.js";
import { academyContractTerms } from "../../core/contracts.js";
import { formatWeeklyWage, seasonYear } from "../format.js";
import { Flag } from "../components/Flag.js";
import { PlayerRatingsTooltip } from "../components/PlayerRatingsTooltip.js";
import { PotDisplay } from "../components/PotDisplay.js";
import { SortableTh, useTableSort, sortRows } from "../components/SortableTable.js";
import { ROSTER_CAP } from "../../core/constants.js";

type AcademySortKey = "name" | "pos" | "ovr" | "pot" | "age" | "wage" | "contract";

/**
 * The user's youth-academy holding pool: prospects generated by their own
 * club's youth intake, sitting on a flat stipend until promoted to the
 * senior roster or released. See CLAUDE.md's "Academy" section.
 */
export function Academy() {
  const {
    league, promoteFromAcademyAction, extendAcademyContractAction, releaseAcademyPlayerAction,
    simming,
  } = useLeague();
  const { sort, toggle } = useTableSort<AcademySortKey>("ovr", "desc");

  if (!league) {
    return <p className="p-3">Loading...</p>;
  }

  const userTeam = league.teams.find((t) => t.tid === league.meta.userTid);
  const academyRoster = (userTeam?.academyRoster ?? [])
    .map((pid) => league.players.find((p) => p.pid === pid))
    .filter((p): p is NonNullable<typeof p> => p != null);
  const academyPlayers = sortRows(academyRoster, sort, {
    name: (p) => p.name,
    pos: (p) => p.pos,
    ovr: (p) => p.ovr,
    pot: (p) => p.potential,
    age: (p) => league.season - p.born,
    wage: (p) => p.contract.salary,
    contract: (p) => p.contract.expiresSeason,
  });

  const atRosterCap = (userTeam?.roster.length ?? 0) >= ROSTER_CAP;
  // Wages are paid up front each season, so a mid-season promotion charges
  // the new senior contract's full season salary at promotion time.
  const midSeason = league.phase === "regular";

  return (
    <div className="container-fluid p-3">
      <h4>
        Academy
        <HelpHint>
          Your youth holding pool. Prospects here draw a cheap flat stipend and don't count against
          your senior roster. Promote one to the first team when he's ready, or extend/release him.
          Only your club has an academy.
        </HelpHint>
      </h4>
      {atRosterCap && (
        <div className="alert alert-warning">
          Your senior roster is full ({ROSTER_CAP}/{ROSTER_CAP}). Release a player before
          promoting another.
        </div>
      )}
      {academyPlayers.length === 0 ? (
        <p>No players in the academy yet. Check back after your next offseason.</p>
      ) : (
        <table className="table table-striped table-sm">
          <thead>
            <tr>
              <SortableTh sortKey="name" sort={sort} onSort={toggle} defaultDir="asc">Name</SortableTh>
              <SortableTh sortKey="pos" sort={sort} onSort={toggle} defaultDir="asc">Pos</SortableTh>
              <SortableTh sortKey="ovr" sort={sort} onSort={toggle} className="text-end">OVR</SortableTh>
              <SortableTh sortKey="pot" sort={sort} onSort={toggle} className="text-end">POT <PotHelp /></SortableTh>
              <SortableTh sortKey="age" sort={sort} onSort={toggle} className="text-end" defaultDir="asc">Age</SortableTh>
              <SortableTh sortKey="wage" sort={sort} onSort={toggle} className="text-end">Wage</SortableTh>
              <SortableTh sortKey="contract" sort={sort} onSort={toggle} className="text-end">Contract</SortableTh>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {academyPlayers.map((p) => (
              <tr key={p.pid}>
                <td>
                  <PlayerRatingsTooltip player={p}>
                    <Link to={`/player/${p.pid}`}>{p.name}</Link>
                  </PlayerRatingsTooltip>{" "}
                  <Flag nationality={p.nationality} />
                </td>
                <td>{p.pos}</td>
                <td className="text-end">{p.ovr}</td>
                <td className="text-end"><PotDisplay player={p} /></td>
                <td className="text-end">{league.season - p.born}</td>
                <td className="text-end">{formatWeeklyWage(p.contract.salary)}</td>
                <td className="text-end">
                  {p.contract.expiresSeason <= league.season
                    ? "Final year"
                    : `Through ${seasonYear(p.contract.expiresSeason)}`}
                </td>
                <td className="text-end">
                  <div className="d-inline-flex gap-1">
                    {canExtend(p, league.season) && (() => {
                      const terms = academyContractTerms(league.season);
                      return (
                        <button
                          className="btn btn-sm btn-outline-success text-nowrap"
                          disabled={simming}
                          onClick={() => extendAcademyContractAction(p.pid)}
                        >
                          Extend {terms.lengthSeasons}y &middot; {formatWeeklyWage(terms.salary)}
                        </button>
                      );
                    })()}
                    {(() => {
                      const unaffordable =
                        midSeason && contractTerms(p, league.season).salary > (userTeam?.budget ?? 0);
                      return (
                        <button
                          className="btn btn-sm btn-primary text-nowrap"
                          disabled={simming || atRosterCap || unaffordable}
                          title={
                            unaffordable
                              ? "Mid-season promotions charge the season's wages up front"
                              : undefined
                          }
                          onClick={() => promoteFromAcademyAction(p.pid)}
                        >
                          Promote
                        </button>
                      );
                    })()}
                    <button
                      className="btn btn-sm btn-outline-danger"
                      disabled={simming}
                      onClick={() => releaseAcademyPlayerAction(p.pid)}
                    >
                      Release
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}
