import type { ChangelogEntry } from "../types.js";

const entry: ChangelogEntry = {
  date: "2026-08-13",
  title: "Positions now decide how a team plays, and a player's position can change",
  items: [
    "Team strength is now built slot by slot from the shape you picked, rather than from what kind of player each man is. Before this, a player counted toward his own position's strength wherever he actually stood, which had a strange consequence: pushing a centre-back into the striker slot made the defense better, because he stayed in the defensive group at full strength and simply left the attacking one. Now the job a player is doing is what counts, and being out of position costs him. Covering a nearby spot is a modest hit a good player can absorb, being played somewhere unrelated is a real downgrade, and an outfielder in goal is a disaster, which is why that is not allowed at all. Roughly, a good player one position out of his own performs like an ordinary player in his proper place.",
    "The substitute bench was the part of the game this fixed most. Replacements used to be picked by exact position or else by whoever was best available, so a tired centre-back was often answered with a striker: 37% of all substitutions put a player in a position unrelated to his own, and a striker replacing a centre-back was the single most common swap in the game. Substitutions now weigh the cost of the slot a player is coming into, and that figure is 0.2%. About 19% fewer substitutions are made overall, because holding a tired starter on often beats wrecking the shape. Chasing a game still works as before: an attacker sent on late plays his own position and the side genuinely lines up with one fewer defender. Title races came out slightly more open as a result, since a side can no longer stumble into a lopsided shape its quality does not justify.",
    "Players now have secondary positions. A player profile shows what he would be rated at every spot he can cover, with his listed position highlighted. Where he is genuinely good at a nearby position for his kind of player, it counts as a real second position: it appears next to his name as \"W / FB\", it is starred on his rating strip, and he plays there with no out-of-position penalty at all. About a third of players in a new world have a second position and only a handful have a third. That share climbs over a long save to around half by season 20 and then holds steady, because players broaden as they develop, so a veteran squad really is more flexible than a young one. Keepers are always keepers.",
    "This changes how a team picks itself. A versatile player is treated as a first-choice option for every position he actually plays, so a better winger who also plays full-back will take the full-back slot ahead of a weaker specialist, where previously the specialist always got it. He is judged on his rating at the slot being filled rather than at his own position, which matters: comparing a winger's winger rating against a striker's striker rating and then playing the winner up front measurably cost teams goals.",
    "A player can also change position permanently. If he has been clearly better at a nearby position for several seasons running, not merely in one good year, that position becomes the one he is listed at. His rating is then calculated as that kind of player, so it usually rises, and his wage and transfer value follow. This cannot be ordered and is not random. It comes out of how he has developed: a player's strongest attributes get harder to improve as he grows, so a sharp specialist gradually broadens, and occasionally he broadens far enough that another job suits him better. It happens most in a player's early and middle twenties, and it is uncommon, running at well under one percent of rostered players a season. A new world starts with nobody miscast, so nothing moves in the opening seasons. Conversions appear on the news feed for your own players and for established players elsewhere, and a player's profile keeps the record.",
    "Two smaller additions come with this. On the pitch view, anyone lined up away from his listed position is labelled with both his position and the slot he is filling, in amber where it costs him and in green where he covers the spot for free, so the cost is never paid unknowingly. On a player's profile, a rating strip shows what he would be worth at each position he can cover, and a converted player's profile records where he came through and when he moved.",
  ],
};

export default entry;
