import type { ChangelogEntry } from "../types.js";

const entry: ChangelogEntry = {
  date: "2026-07-25",
  title: "Your players go to the World Cup now",
  items: [
    "I added international football. Your players represent their countries in the summer, on a four-year cycle: there's a World Cup every fourth season, and the three offseasons before it each play a round of qualifying (a proper long home-and-away campaign, not a one-off). The 16 who make it play the World Cup itself: four groups of four, then quarter-finals, semis and a final. It all happens between seasons, so it doesn't touch your league at all, and there's a whole National Teams section in the sidebar where you can follow it.",
    "Nobody manages a national team, not even you. Each country just picks its best available squad, so the whole thing is really about developing players good enough to get called up and then watching how they do. Every nation with enough players in the world enters qualifying, and confederations that actually have strong teams get more places, so the field ends up looking like it should.",
    "One thing I like: squads are picked from the shape your players are in at the end of the club season, injuries and all. So if your star pulls up injured in May, he genuinely misses the tournament. It also plays out before anyone retires now, so a veteran in his last season gets one final shot at it. Caps, goals, tournaments and titles all build up on each player's profile over his career. For now the only way any of it touches your club is injuries: if a player gets hurt at the World Cup or in qualifying, part of it heals over the summer, but a serious injury carries into the new season and he misses the opening weeks (a minor knock clears up before kickoff). His value and development still aren't affected by international stuff, and I left tournament tiredness out for now.",
    "You play the tournament yourself instead of it all resolving in one silent step. When you hit the offseason in an international summer, the Dashboard gives you buttons: play qualifying in a qualifying year, or play the group stage, then the quarter-finals, then the semis, then the final in a World Cup year, one at a time so you can actually watch it happen. There's a 'sim through the World Cup' button if you'd rather skip ahead, and you can't advance to the next season until it's done.",
    "There's a proper National Teams section in the sidebar now, not just one page. It's got the current World Cup and Qualifying (and you can flip back to past years), a Rosters tab with every nation's squad for whatever campaign is being played, a Schedule of fixtures (it opens on the qualifying round being played right now, because a full campaign is about 280 games and drawing all of them at once made the page crawl), Power Rankings of every nation with how they've moved, Stat Leaders for both the best nations and the best players (filter it to one country to see who your guys are up against), and a History tab with past winners and each nation's record. Old tournaments keep their results and tables so you can look back on them, I just don't hang onto every single box score forever or the save would balloon.",
    "The Rosters tab is the one I keep clicking on myself. Pick a nation and you get its whole squad, best nations first, with the eleven it would actually field highlighted, everyone's club, and their caps and international goals. It's a quick way to see how many of your own players made it and who they're competing with for a shirt. And on a player's profile there's now a National Team tab next to League and Cup, breaking his international record down campaign by campaign instead of just showing the career totals. That one only fills in going forward, since I never stored the per-campaign detail before.",
  ],
};

export default entry;
