import type { ChangelogEntry } from "../types.js";

const entry: ChangelogEntry = {
  date: "2026-08-22",
  title: "Build your own world",
  items: [
    "**New League** has a **World setup** panel now. You choose which of the eight countries are in your save, and you can add leagues of your own on top of them. None of it can be changed later, so it's worth a minute before you start.",
    "A league you add gets its own settings: how strong its squads are, how much money its clubs have, and how many places it sends to the Continental Cup and the Continental Shield. Its clubs get generated names and colours, same as the rest of the game's fictional clubs.",
    "You pick its **shape** too. One division or two, and anywhere from 8 to 20 clubs in each. Two divisions works like every country already in the game, with 3 up and 3 down; one division means nothing is promoted or relegated there. Sizes are even numbers only, since the fixture list pairs clubs off each round, and 20 is the ceiling because a 20-club season already fills the 38-matchday calendar exactly. A smaller division plays fewer games and takes blank matchdays through the year rather than finishing in March, so its run-in still lines up with everyone else's. There's no third division.",
    "**Strength is the one to get right.** It runs 0 to 20 and higher is stronger, with 20 level with England, Spain, Italy and Germany. Each point below that is worth about 1 OVR across the squads. In terms you can picture: at 15, where France sits, the league's champion is about as good as England's 5th best club. At 10, near Portugal, it's about the 12th. At 2 your champion is weaker than the worst club in England. There's a table in the panel showing where every league already in the game sits, so you have something to aim at rather than a bare number.",
    "Money follows strength unless you tell it not to. You can unlink them, but a weak league with big money creeps up the pecking order over a long save until it sits above leagues it has no business beating, so you get a warning when you set one up that way.",
    "Each league you add has its own **Import roster** button, so you can bring real clubs and squads into it. It takes the same roster files as the full import, but it only touches that one league, and it doesn't care what the file calls its competitions: the first one in the file fills the top division and the second fills the one below. So a file written for somebody else's world drops straight into a league you just invented. Any club slot the file doesn't cover keeps the invented club it came with.",
    "Whatever numbers you pick, the **Shield starts exactly where the Cup stops** in each league. Send 1 to the Cup and 3 to the Shield and you get your champion in the Cup and 2nd through 4th in the Shield. No club ever ends up in both, and no place goes unused.",
    "**Giving a league places doesn't take them off anyone else, as long as the total comes out right.** Everyone keeps their own allowance and the competition just gets bigger. The catch is that a field can only be certain sizes, going up in fours from twelve, so if the world asks for a total in between, the field is cut back to the size below and the lowest-placed qualifiers anywhere miss out. Add a ninth league taking 2 and the world asks for 26 Cup places, plays 24, and two of the big four lose their fourth spot. Your new league keeps both of its own, because its champion and runner-up outrank every 4th-placed club in the world. Give it 4 places instead and the total lands on 28 and nobody loses anything.",
    "The **Shield counts separately** and it's the one to watch, since every league sends it 2. Any ninth league takes it from 16 to 18 and trims two clubs no matter what you did with the Cup. Switching one of the eight countries off keeps both totals clean. You get a warning either way, telling you how many clubs a bad total would cost.",
    "There's a **Name the clubs yourself** tick box on the same screen. Turn it on and you get an editor once the world is built, with every club in every competition listed: name, three-letter abbreviation, and both colours. It covers the leagues you invented too, and nothing is saved until you're done with it. The editor itself isn't new, it just used to be tucked behind the Customize Teams button on the Leagues page where nobody building a world would find it.",
    "Saves you're already playing are untouched, since this only shapes a world at the moment you create it.",
  ],
};

export default entry;
