import type { ChangelogEntry } from "../types.js";

const entry: ChangelogEntry = {
  date: "2026-07-30",
  title: "Retirement now depends on whether anyone actually wanted you",
  items: [
    "Retirement was embarrassingly simple before this and I don't think many people noticed, which is sort of the problem. It was pure age. Nobody could retire before 33, and after that everyone rolled the same dice. A 33-year-old who was the best player in your league and a 33-year-old who couldn't get off the bench had exactly the same chance of packing it in. How good you were never entered into it at all.",
    "Now two things decide it. Age still does most of the work, but whether a club actually had you on their books last season scales it. Hold down a squad place and your odds drop by about 40%, which is enough that a player good enough to keep playing can still be going at 39 or 40 instead of almost certainly being gone by 38. It's not a free pass and there's no age where a great veteran is safe, he just lasts as long as he's worth a place, which is how it should have worked all along.",
    "The other end of it is that players nobody signs now drift out of the game, at any age. Before, someone who never got picked up just sat in the free agent pool from 16 until he turned 33, because that was the first age retirement could touch him. So the pool filled up with people who were never going to play again and never went anywhere. Now, going a full season with no club starts the clock whether you're 19 or 35. There's a grace period so this can't blindside you: a contract simply running out doesn't count against a player, so everyone gets one full free agency to find a club first.",
    "One deliberate exception, because the first version of this was too brutal. Genuine young prospects don't wash out. If a player is still in his early twenties and his ceiling is high he'll wait around for his shot however long it takes, so the promising kids on your Incoming Talent page aren't on a timer. It's the journeymen who clear out, and an unsigned 30-year-old is done no matter how good he used to be. What you'll notice is that the free agent list is a bit thinner and a bit older than it used to be, and someone you passed on twice might not be there a third time.",
    "And since a lot more players leave the game now, you should probably get to see who. The Season Preview has a Retirements section: how many players called it a career this offseason, how many of them were actually on a club's books, and then the biggest names to go, with the club they last played for, how many seasons they got, and their career goals and assists. Anyone you lose from your own squad is always in there, however low his rating, because that's the one you care about. It's only the biggest names by design, since most of the players retiring in any given offseason are unsigned ones you've never heard of, and I'm not putting a two thousand row table on a page again.",
    "Worth being upfront about one thing while I'm here: a retired player is deleted, not archived. There's no career page to go and visit afterwards, and old transfer entries about him lose his name. That's how it's always worked, it just happens more often now, and the Season Preview list is currently the only send-off he gets. A proper hall of fame for retired players is a bigger job and I haven't done it.",
    "The Manual has said for a while that \"declining veterans and marginal players go first\" and that a still-elite 34-year-old will often play on. That was wishful thinking on my part, it was never true, and it is now.",
  ],
};

export default entry;
