import type { ChangelogEntry } from "../types.js";

const entry: ChangelogEntry = {
  date: "2026-08-29",
  title: "Four new countries: the Netherlands, Greece, Scotland and Serbia",
  items: [
    "New saves now span **twelve countries** instead of eight. The Netherlands, Greece, Scotland and Serbia each arrive with a full two-division pyramid, taking the world to **24 leagues and 420 clubs**. All four are pickable at the start like any other country. Existing saves keep the country set they were created with, so nothing expands mid-save.",
    "The Netherlands slots in between France and Portugal, which is roughly where the real UEFA coefficient puts it. The other three go in below Turkey, in the order Greece, Scotland, Serbia, with Serbia the weakest league in the game and the poorest.",
    "One thing I'd rather say than pretend otherwise: the bottom of the ladder converges over a long save. I gave Scotland a deliberately wide step down from Turkey to try to make it stick, ran 20 seasons across four different saves to check, and it doesn't — Scotland starts a clear 1.8 OVR below Turkey and finishes level with it. Weaker leagues develop players faster than the big four do, so the further down a gap sits the quicker it closes, no matter how wide I open it. The order is real when you start a save, and by season 20 the bottom few leagues are bunched. The Netherlands, higher up, holds its gap on every save I tested.",
    "Money follows strength, the same as everywhere else on the ladder, right down to Serbia at the bottom. I keep those two things in the same order for a reason: a richer league climbs over a long save, so if a weaker league out-earns a stronger one, the two just swap places inside twenty seasons and the ladder stops meaning anything.",
    "Squad nationalities come from each league's real breakdown, and the four are genuinely different from each other. Serbian squads are **66% domestic**, the most domestic league in the game, because Serbia produces and exports rather than imports. Dutch squads are a bit over half Dutch with the rest spread very wide, which is what a selling league looks like. Greek squads are the opposite, under half domestic. Scottish squads are only **36% Scottish**, the least domestic league in the game, and England on its own is nearly a quarter of everyone else.",
    "Two of those surprised me enough that I went and checked the real numbers rather than trusting what I'd assumed. The biggest foreign contingent in Greece isn't Brazilian or Balkan, it's **Spanish**. And the biggest one in Serbia isn't from a neighbouring country at all, it's **Ghanaian** — the West African intake there outweighs the ex-Yugoslav one. Both are now in the game the way they actually are rather than the way they sound like they should be.",
    "**Leagues are now the size they are in real life**, which they weren't before — every division in the game used to field 20 clubs regardless of country. England, Spain and Italy still field 20. Germany, France, Portugal, Turkey and the Netherlands field 18, Belgium and Serbia 16, Greece 14, and Scotland 12, with second divisions to match, down to Scotland's 10. The world goes from 480 clubs to 420. Twenty stays the ceiling because a division that size already fills every matchday there is; a smaller league spreads its games over the same calendar instead of finishing in March, so the transfer windows and the run-in still land where you expect. One thing to keep in mind reading a table: a smaller league plays fewer games, so its champion's points total is lower and isn't comparable to a 20-club league's.",
    "Promotion and relegation scale with that. Most countries still swap three clubs each way, but Portugal, Belgium, the Netherlands, Greece and Serbia swap two, and Scotland one. Three up out of a 10-club second division would have turned over a third of it every season.",
    "Giving leagues real sizes turned up a bug that a flat 20 had been hiding, and it was a big one. In the offseason every club in the world queues up for the free agents, worst club first, and the queue was ordered by **raw points**. A 12-club league plays 22 games, so its clubs always had fewer points than a 20-club league's and went to the front of the queue however good they were, and the best free agents were gone by the time the big leagues got a turn. In a test world of six identical leagues differing only in size, the 12-club ones were signing free agents averaging 39 OVR while the 20-club ones got 26. Over twenty seasons that was enough to make Scotland, which starts as the second-weakest league in the game, the strongest one in it. The queue is by **points per game** now. Nothing changes for any league where every club has played the same number of games, which is every league there was before this update.",
    "Prize money had the same problem in a smaller way. Top-five and top-ten money went to the 5th and 10th placed clubs, which in a 10-club division meant everyone got paid. It's a share of the table now, so half the division is paid whatever its size, and the 20-club leagues are untouched.",
    "The Continental Cup grows from 24 clubs to **32**, and the Continental Shield from 16 to **24**, because both fields are sized off the number of countries. Four more countries is eight more Cup places and eight more Shield places. Those extra Cup places go into the same pot everyone competes for on coefficient, so nobody is handed places for free. The format is otherwise unchanged: one league phase of six games, top four straight into the quarter-finals, 5th through 12th into the playoff round. Bigger field and the same knockout stage, so 13th through 32nd now go out at the league phase.",
    "Both continental fields have to be a multiple of four, which is a real constraint rather than a detail: the league-phase draw splits the field into two halves and pairs everyone inside them, so an odd half can't be drawn. Since the Cup works out to twice the number of countries plus eight and the Shield to exactly twice, **the world needs an even number of countries** or clubs that qualified on league position get cut. That's why four countries went in rather than three.",
  ],
};

export default entry;
