import type { ChangelogEntry } from "../types.js";

const entry: ChangelogEntry = {
  date: "2026-08-08",
  title: "Transfers now behave like football: stars stay put, and won't drop to small clubs",
  items: [
    "The transfer market had three linked faults, and they were bad enough to make a save read like a different sport. Measured across twelve-season dynasties: 56% of every player rated 78 or above changed club each season, the median gap between one move and that player's next was a single season, 17% of star moves were to a squad weaker than the one he left, and there were 42 fees of $100M or more per season. World-class players routinely turned up at small clubs.",
    "The root cause was that a club valued its own players with the same formula it used to value other clubs' players. That formula asks how much a player would improve you, so a club's own best player scored zero (he is already the best it has) and was marked down again for being expensive to buy, despite already being on the books. The effect was that the worse a club was, the more it valued a star. On a real save, the five highest bidders for the best player in the world were all among the weakest clubs in it: one with a squad rating of 51.9 valued him at $538M, while his own club valued him at $132M. He was therefore always cheap and always available.",
    "Clubs now price their own players by a different question: not how much he would improve them, but how far they would fall back without him. A star with no ready deputy costs a fortune to prise away; one with a good understudy does not. A club also no longer writes off its own young talent because it is chasing the title this season.",
    "Players also have a say now, which is the piece football needs and basketball does not. Basketball has a salary cap, so a star genuinely can end up somewhere small because only that team had room. Football has no such mechanism, and nothing in the game was standing in for the player's own preference. The better a player is, the more he weighs the size of the club he would be joining, measured on squad quality and fame together. A fringe player goes wherever the game time is; a genuine star will move sideways or upward but will not drop to a much smaller club at any price. A player who has only just joined somewhere is also much harder to move again, easing off over about three seasons. This applies to your club exactly as it applies to the AI, so a target who would turn you down now says so on the row instead of silently swallowing the offer.",
    "Fees were rebalanced at the same time. Player values had been pinned to real Premier League transfer fees, which looked right in isolation but not against this game's economy, where a club's base season income is $88M rather than a real club's several hundred million. A $120M fee was costing about 1.4 seasons of a club's entire income, against roughly 0.2 for the real transfer it was copied from. On top of that the elite end of the value curve saturated: every player rated 80 or above priced identically at the $350M ceiling, so an 80 and an 87 cost the same, and every elite deal opened at $175M. Values now scale to what clubs actually earn here and keep climbing across the elite band instead of flattening.",
    "After the changes, across the same dynasties: 9-10% of players rated 78 or above change club in a season, 1-3% of those moves are to a weaker squad, and fees of $100M or more run at 4 to 6 per season across the whole world instead of 42. The largest fee seen fell from $346M to somewhere between $172M and $251M depending on the save. The player bought at that price is now typically rated 80 rather than 75, though he is still usually in his early twenties, which is true to life. Selling players brings in less than it used to, which is the intended trade: a nine-figure fee is meant to be a headline, not the going rate for a decent squad player.",
  ],
};

export default entry;
