import type { ChangelogEntry } from "../types.js";

const entry: ChangelogEntry = {
  date: "2026-08-31",
  title: "Your academy is now a real decision, and rival clubs stopped binning theirs",
  items: [
    "A player told me the Incoming Talent page made winning titles far too easy. He was right, and more right than he knew, because when I went looking the cause turned out not to be that page at all.",
    "**Every AI club was throwing away its own youth, every single year.** When clubs trimmed their squads in the offseason they ranked players purely on how good they were *right now*, and a 16-year-old is always bottom of that list. So 84% of every club's youth intake got released the same summer it arrived, wonderkids included, and nothing ever signed them back, because free agency ranked on current rating too. Nobody in the world valued potential except you.",
    "That left a pile of other clubs' abandoned talent that only ever grew: about 1,500 unsigned kids by your second season, over 3,000 by your seventh, restocked with roughly 150 genuinely promising ones a year. I took the ten best available in season two, all free, all £500 a week in the academy, and left them alone. By season eleven they were rated 84, 83, 82, 79, 79, 79, 71 and 71. A typical top-flight starter is 66. That's a title-winning spine for nothing, and the pile refilled every summer.",
    "**Clubs now keep their best young players.** Each one hangs on to a handful of its most promising kids regardless of current rating. They're carried on top of the squad rather than in place of anyone, so it doesn't change who gets picked on a Saturday, and it barely costs them anything in wages. What it does mean is that the free market is now genuinely players nobody wanted, which is what it should always have been.",
    "**So the youth route is your own academy, and it's an actual decision now.** Incoming Talent is gone, replaced by a **Youth Intake** page. Every summer your academy turns up a group of ten to twelve 16-year-olds on trial. You can offer contracts to five. The rest leave and are free for anybody to sign, so passing on the wrong one is a mistake you get to watch happen somewhere else. You're picking on estimated ceilings rather than real ones, which is most of the difficulty.",
    "**Scouting money finally buys you something other than clearer numbers.** How good your intake is now depends on what you spend on scouting and how much buzz there is around the club, alongside your academy's standing and how you've been finishing. It's worth a few rating points across the whole group at full tilt. Small in any one year, but it stacks up over a decade of intakes, and it gives the scouting budget a reason to exist beyond narrowing a potential range.",
    "**You can also send your scouts out with instructions.** There's a **Scout directions** panel on the Youth Intake page with three things you can set, all of them taking effect at your next intake rather than the group already sitting there.",
    "**Countries**, up to three, and they'll turn up most of next summer's group between them, with the rest still coming from around your own league. Worth being straight about this one: your scouts find you *different* players, not better ones. Where a kid is from decides his name and which country can pick him, never how good he is. That second part is the whole point, though, if you fancy building a national team out of players you brought through yourself.",
    "**Positions**, up to three, for when you can see a hole coming in a few years and would rather start filling it now. It leans the group hard rather than filtering it, so you'll get a lot of what you asked for and never only that.",
    "**And what kind of player**: athletes, ball players, or readers of the game. This one is a trade rather than an upgrade, and I'd rather say so than let you find out. Ask for athletes and they arrive quicker, stronger and fitter, and give back exactly as much in the parts of their game you didn't ask for. They're worth the same as the players you'd have got anyway. They just play differently, which is useful if you want a squad with a particular character or a formation that leans on one thing, and useless if what you wanted was better players.",
    "One caveat on those last two. The handful of kids your academy turns up on its own arrive as they are, so positions and type of player shape most of the group rather than all of it. Countries cover everyone, because that only changes where a player is from.",
    "Unsigned players of every age now share the **Free Agents** page, since there's no longer a separate class of young ones worth browsing on their own.",
    "If you're mid-save none of this touches your existing squad or your academy. Your first trial group turns up at your next offseason.",
  ],
};

export default entry;
