import type { ChangelogEntry } from "../types.js";

const entry: ChangelogEntry = {
  date: "2026-08-29",
  title: "You can manage a national team",
  items: [
    "International football has always run itself. Every nation picked its own squad, played its own qualifying and its own World Cup, and the most you could do was develop players good enough to get called up and then watch them go. **Now you can take one of those jobs.**",
    "Pick a country on the New League screen, in the new **National team** box under Difficulty, or leave it as **None** and wait for someone to ask. Federations get in touch over the summer and anything on the table shows up on the new **Federation** page. It's entirely optional, a save with no country plays exactly the way it always did, and most of my own saves probably still will.",
    "**My Squad** is where the job happens. A squad gets named for you when a campaign is drawn, at the end of a season, and you can pull it apart before the first match: call anyone eligible into the 23, drop anyone you don't fancy, pick a shape, and drag your eleven around the same pitch you use on your club's Roster page. You can change the eleven again between rounds.",
    "A few rules and limits worth knowing before you start:\n- You have to take a **goalkeeper**, and only a goalkeeper can go in goal.\n- There's **no transfer market, no budget and no training.** A national manager picks from who exists, and that's the whole job.\n- A qualifying campaign runs across **three summers**, so if anyone in the eleven you picked can't play on the day, the game picks that whole eleven for you rather than field ten. It won't leave you a man short, but it's worth looking in between rounds.\n- The countries your leagues are in have the deepest pools. Anywhere else depends on how many of its players happen to be born into your world, and a country needs **18** of them plus a keeper to enter anything. You'll be told if the one you picked doesn't clear that.",
    "**The federation judges you once per campaign**, not once per season: after qualifying ends, after a World Cup, after a continental championship. They weigh how far you got against how good your players are, and that bar is read off your country's best available eleven rather than the squad you actually named. Leaving your stars at home lowers nothing except your chances.",
    "Qualifying is the one that can really hurt. Missing out when you were expected to go is the worst thing that can happen to an international manager, and getting there when nobody expected you is the best. Winning a World Cup buys you years.",
    "Confidence works like the club version, bar and all, with the same **Never sack me** switch. The one real difference is that **being let go by a country is an ordinary place to end up.** There's no scramble for another job the way there is when a club sacks you, you just go back to club football until someone else asks, and you can step down whenever you like. Your international career is kept alongside your club one: every country you've run, campaigns managed, times you qualified, continental titles and World Cups, and how each spell ended.",
    "**Existing saves are untouched and start with no country**, which is what they've been playing all along, so take a job the next time one's offered. Nothing is invented for the seasons behind you, because those tournaments were played with nobody in charge and crediting you with them would be a lie.",
    "One last thing, since it's the question I'd ask: none of this can change your club game. International matches have always run on their own separate rolls, and so does everything here, right down to which countries come calling. Managing Brazil doesn't move a single result in your league.",
  ],
};

export default entry;
