import type { ChangelogEntry } from "../types.js";

const entry: ChangelogEntry = {
  date: "2026-09-03",
  title: "Sell-on clauses and bonuses",
  items: [
    "Every deal you negotiate now has an **Add-ons** panel under the offer buttons, on both the Transfers page and Incoming Offers.",
    "A **sell-on share**, up to 40%. Sell a player with one attached and you keep that share of the **profit** if his new club moves him on again within 5 seasons. Profit is the word that matters: if they sell him for less than they paid you, you get nothing.",
    "And **bonuses**, paid once each if the thing happens within 3 seasons while he's still at that club. Up to four of them: league games played in a season, league goals in a season, his new club qualifying for Europe, his new club winning promotion. Together they can't come to more than half the cash fee.",
    "**The bonuses you're offered are picked for the player**, which I think is the part that makes them worth using. You won't be offered a goals bonus for a goalkeeper, or a promotion bonus when the club buying him is already in the top flight, because neither could ever pay out. And the target moves with the player: a squad man might be offered a bonus at 14 league games where a first-choice signing gets one at 31. They're all set to be about equally likely to pay, so the number itself tells you something about how his new club rates him. You can change the money; you can't change the target.",
    "**Add-ons sit on top of the fee**, the way a transfer actually gets reported: $20M rising to $25M. They don't change what you pay or get today. What they change is whether the other club says yes, because they weigh your cash *and* what your add-ons are likely to be worth to them.",
    "That's the whole use of them. Buying, they're how you land someone you can't quite afford: bid under his price, promise a cut of any future sale, and the deal can clear even though the cash alone wouldn't have. It's how a lot of real transfers get done.",
    "Selling works the same way in reverse, and it's the bit worth understanding. Asking for a sell-on *as well as* the money is asking for more than they offered, so a club will only wear it while the whole package still sits under what the player is worth to them. When it doesn't, the Accept button greys out and you have to counter. That's deliberate: if you could pocket the full fee and a sell-on for nothing, you'd do it on every deal without thinking and it'd stop being a decision.",
    "A sell-on fires whenever the club that owes it sells him, including years later to a third club you've never dealt with. Everything you're owed and everything you owe is listed under **Transfer Add-ons** on the Finance page, and on the player's own page. Rows drop off those lists the moment they pay, run out of time, or he leaves the club that owed them. A bonus dies unpaid if he's sold before it triggers, and a sell-on settles and ends the moment he's sold on.",
    "Getting the price right took measuring rather than guessing, and my first guess was bad. I built a tool that replays 24,000 real transfers and asks what a clause would have been priced at against what it would actually have paid. My first version charged you nearly **twice** what a sell-on was worth, because it assumed players get resold at a profit and mostly they don't: only **40%** of resales are for more than the club paid.",
    "The bonuses took three goes, and the mistakes are more interesting than the fix. First I just had the rates wrong. Then, once each bonus could ask for a different number, I had to work out how the price should change with the target, so I measured 25,000 real player-seasons: how often a signing actually plays, and how often he scores, split by position and by how much better he is than the man he's replacing. That turned up things I'd have got wrong by feel. Being *much* better than the incumbent barely helps compared to being a bit better, because there are only so many games. And a striker scores twenty-four times as often as a centre-back, which dwarfs anything being a good player does within a position.",
    "The last one was my own fault twice over. Bonuses were still coming out about twice too expensive, because I was pricing them over the full three years when a bought player is only still at that club for about **one** of them on average. I'd actually spotted that effect earlier and deliberately excluded these two bonuses from the correction, for a reason that was true at the time and quietly stopped being true when I rewrote the model. All corrected now, and everything prices within a few percent of what it really pays. A bonus you'd never sensibly take is worse than no bonus at all.",
    "One limit worth knowing: this is yours only. AI clubs don't put add-ons on each other's deals yet. Letting them would change how money moves between every league in the world, which needs a lot more testing than letting you do it does.",
    "Existing saves are fine. There were no clauses before, so there's nothing to convert, and nothing about how the rest of the world trades has changed.",
  ],
};

export default entry;
