// Emoji flag lookup for each nationality string produced by
// `pickNationality` (see ./nationalities.ts). England/Scotland/Wales use the
// regional-subdivision flag emoji (not the UK flag) since PL squads track
// home nations separately.
const FLAGS: Record<string, string> = {
  England: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  Scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  France: "🇫🇷",
  Brazil: "🇧🇷",
  Spain: "🇪🇸",
  Portugal: "🇵🇹",
  Netherlands: "🇳🇱",
  Belgium: "🇧🇪",
  Argentina: "🇦🇷",
  "Republic of Ireland": "🇮🇪",
  Denmark: "🇩🇰",
  Germany: "🇩🇪",
  Nigeria: "🇳🇬",
  Croatia: "🇭🇷",
  Norway: "🇳🇴",
  Sweden: "🇸🇪",
  Poland: "🇵🇱",
  Ukraine: "🇺🇦",
  Ghana: "🇬🇭",
  Serbia: "🇷🇸",
  Cameroon: "🇨🇲",
  "Ivory Coast": "🇨🇮",
  "United States": "🇺🇸",
  Switzerland: "🇨🇭",
  Japan: "🇯🇵",
  "South Korea": "🇰🇷",
  Austria: "🇦🇹",
  "Czech Republic": "🇨🇿",
  Turkey: "🇹🇷",
  Algeria: "🇩🇿",
  Morocco: "🇲🇦",
  Senegal: "🇸🇳",
  Mexico: "🇲🇽",
  Canada: "🇨🇦",
  Australia: "🇦🇺",
  Finland: "🇫🇮",
  Romania: "🇷🇴",
  Slovakia: "🇸🇰",
  Slovenia: "🇸🇮",
  Iceland: "🇮🇸",
  Mali: "🇲🇱",
  "Burkina Faso": "🇧🇫",
  "DR Congo": "🇨🇩",
  Guinea: "🇬🇳",
  Uruguay: "🇺🇾",
  Colombia: "🇨🇴",
  Ecuador: "🇪🇨",
  Paraguay: "🇵🇾",
  Venezuela: "🇻🇪",
  Egypt: "🇪🇬",
  Tunisia: "🇹🇳",
  Chile: "🇨🇱",
  Peru: "🇵🇪",
  Bolivia: "🇧🇴",
  Iran: "🇮🇷",
  China: "🇨🇳",
  India: "🇮🇳",
  Israel: "🇮🇱",
  "New Zealand": "🇳🇿",
  Jamaica: "🇯🇲",
  "Costa Rica": "🇨🇷",
  Honduras: "🇭🇳",
  Panama: "🇵🇦",
  Zambia: "🇿🇲",
  Kenya: "🇰🇪",
  Gabon: "🇬🇦",
  Angola: "🇦🇴",
  Tanzania: "🇹🇿",
  "South Africa": "🇿🇦",
};

/** Emoji flag for a nationality string, or a placeholder flag if unknown. */
export function flagFor(nationality: string): string {
  return FLAGS[nationality] ?? "🏳️";
}
