// Maps each nationality string produced by `pickNationality`
// (see ./nationalities.ts) to an ISO 3166-1 alpha-2 country code — the
// filename of its flag art in src/ui/assets/flags/. England/Scotland/Wales
// use the GB subdivision codes (gb-eng/gb-sct/gb-wls) since squads track the
// home nations separately. The UI (`<Flag>`) renders the matching SVG image;
// flag emoji were dropped because many platforms don't ship them (they showed
// as bare "ES"/"DK" letters instead).
const FLAG_CODES: Record<string, string> = {
  England: "gb-eng",
  Scotland: "gb-sct",
  Wales: "gb-wls",
  France: "fr",
  Brazil: "br",
  Spain: "es",
  Italy: "it",
  Portugal: "pt",
  Netherlands: "nl",
  Belgium: "be",
  Argentina: "ar",
  "Republic of Ireland": "ie",
  Denmark: "dk",
  Germany: "de",
  Nigeria: "ng",
  Croatia: "hr",
  Norway: "no",
  Sweden: "se",
  Poland: "pl",
  Ukraine: "ua",
  Ghana: "gh",
  Serbia: "rs",
  Cameroon: "cm",
  "Ivory Coast": "ci",
  "United States": "us",
  Switzerland: "ch",
  Japan: "jp",
  "South Korea": "kr",
  Austria: "at",
  "Czech Republic": "cz",
  Turkey: "tr",
  // Named only by the Super Lig's nationality table (see UNLISTED_NATIONALITIES).
  "Bosnia-Herzegovina": "ba",
  Gambia: "gm",
  Albania: "al",
  Algeria: "dz",
  Morocco: "ma",
  Senegal: "sn",
  Mexico: "mx",
  Canada: "ca",
  Australia: "au",
  Finland: "fi",
  Romania: "ro",
  Slovakia: "sk",
  Slovenia: "si",
  Iceland: "is",
  Mali: "ml",
  "Burkina Faso": "bf",
  "DR Congo": "cd",
  Guinea: "gn",
  Uruguay: "uy",
  Colombia: "co",
  Ecuador: "ec",
  Paraguay: "py",
  Venezuela: "ve",
  Egypt: "eg",
  Tunisia: "tn",
  Chile: "cl",
  Peru: "pe",
  Bolivia: "bo",
  Iran: "ir",
  China: "cn",
  India: "in",
  Israel: "il",
  "New Zealand": "nz",
  Jamaica: "jm",
  "Costa Rica": "cr",
  Honduras: "hn",
  Panama: "pa",
  Zambia: "zm",
  Kenya: "ke",
  Gabon: "ga",
  Angola: "ao",
  Tanzania: "tz",
  "South Africa": "za",
  Kosovo: "xk",
  Greece: "gr",
  "Cape Verde": "cv",
  "Guinea-Bissau": "gw",
  // Added 2026-08-26 with the expanded nationality set. Nations in that set
  // whose flag needs Arabic calligraphy or a coat of arms are deliberately
  // absent rather than approximated: <Flag> already falls back to a neutral
  // swatch, and a wrong flag reads worse than none.
  "United Arab Emirates": "ae",
  Bulgaria: "bg",
  Benin: "bj",
  Ethiopia: "et",
  Georgia: "ge",
  Hungary: "hu",
  Indonesia: "id",
  "North Macedonia": "mk",
  Qatar: "qa",
  Russia: "ru",
  Sudan: "sd",
  Togo: "tg",
  Thailand: "th",
  "Trinidad and Tobago": "tt",
  Vietnam: "vn",
  // Added 2026-09-01 with the full FIFA nationality set. Only the flags that
  // are exactly reproducible as plain geometry — bands, a disc, a triangle, a
  // star — got art. The rest of that set (a coat of arms, Arabic calligraphy,
  // a dragon, Nepal's double pennon) is deliberately left to <Flag>'s neutral
  // swatch, for the reason the block above gives: a wrong flag reads worse
  // than none.
  Armenia: "am",
  Bangladesh: "bd",
  Botswana: "bw",
  Chad: "td",
  Congo: "cg",
  Djibouti: "dj",
  Estonia: "ee",
  Kuwait: "kw",
  Laos: "la",
  Latvia: "lv",
  Liberia: "lr",
  Lithuania: "lt",
  Luxembourg: "lu",
  Madagascar: "mg",
  Mauritius: "mu",
  Myanmar: "mm",
  Niger: "ne",
  "North Korea": "kp",
  Palestine: "ps",
  "Sierra Leone": "sl",
  Somalia: "so",
  "South Sudan": "ss",
  Syria: "sy",
  Taiwan: "tw",
  Yemen: "ye",
};

/** ISO country code (flag-art filename) for a nationality, or null if unknown. */
export function flagCodeFor(nationality: string): string | null {
  return FLAG_CODES[nationality] ?? null;
}
