// Maps each nationality string produced by `pickNationality`
// (see ./nationalities.ts) to an ISO 3166-1 alpha-2 country code — the
// filename of its flag art in src/ui/assets/flags/. England/Scotland/Wales
// use the GB subdivision codes (gb-eng/gb-sct/gb-wls) since squads track the
// home nations separately. The UI (`<Flag>`) renders the matching SVG image;
// flag emoji were dropped because many platforms don't ship them (they showed
// as bare "ES"/"DK" letters instead).
const FLAG_CODES: Record<string, string> = {
  England: "gb-eng",
  Scotland: "gb-sct",
  Wales: "gb-wls",
  France: "fr",
  Brazil: "br",
  Spain: "es",
  Italy: "it",
  Portugal: "pt",
  Netherlands: "nl",
  Belgium: "be",
  Argentina: "ar",
  "Republic of Ireland": "ie",
  Denmark: "dk",
  Germany: "de",
  Nigeria: "ng",
  Croatia: "hr",
  Norway: "no",
  Sweden: "se",
  Poland: "pl",
  Ukraine: "ua",
  Ghana: "gh",
  Serbia: "rs",
  Cameroon: "cm",
  "Ivory Coast": "ci",
  "United States": "us",
  Switzerland: "ch",
  Japan: "jp",
  "South Korea": "kr",
  Austria: "at",
  "Czech Republic": "cz",
  Turkey: "tr",
  Algeria: "dz",
  Morocco: "ma",
  Senegal: "sn",
  Mexico: "mx",
  Canada: "ca",
  Australia: "au",
  Finland: "fi",
  Romania: "ro",
  Slovakia: "sk",
  Slovenia: "si",
  Iceland: "is",
  Mali: "ml",
  "Burkina Faso": "bf",
  "DR Congo": "cd",
  Guinea: "gn",
  Uruguay: "uy",
  Colombia: "co",
  Ecuador: "ec",
  Paraguay: "py",
  Venezuela: "ve",
  Egypt: "eg",
  Tunisia: "tn",
  Chile: "cl",
  Peru: "pe",
  Bolivia: "bo",
  Iran: "ir",
  China: "cn",
  India: "in",
  Israel: "il",
  "New Zealand": "nz",
  Jamaica: "jm",
  "Costa Rica": "cr",
  Honduras: "hn",
  Panama: "pa",
  Zambia: "zm",
  Kenya: "ke",
  Gabon: "ga",
  Angola: "ao",
  Tanzania: "tz",
  "South Africa": "za",
  Kosovo: "xk",
  Greece: "gr",
  "Cape Verde": "cv",
  "Guinea-Bissau": "gw",
};

/** ISO country code (flag-art filename) for a nationality, or null if unknown. */
export function flagCodeFor(nationality: string): string | null {
  return FLAG_CODES[nationality] ?? null;
}
